### ISSUE TITLE
Setup issue templates and guidelines for project

### ISSUE THREAD

**Issue by radubrehar** [wecross/ministry-scheduler#6]
Maybe this helps https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository - also see related links on that page.

**Comment by andreifloricel** [comment]
Will do, but only towards the end of the week (until then I have a pretty hectic schedule)

**Comment by radubrehar** [comment]
#9 delivers this, also @andreifloricel thanks for #13
